[{
    q: "When will the woman arrive at the hotel?",
    o: ["A. On September 15.", "B. On September 16.", "C. On September 23."],
    answer: 2,
    audio: 19_20,
    origin: [
        "M: Hello, Milton Hotel Reservations. How may I assist you?",
        "W: Hi, I’m calling to make some changes to an existing reservation.",
        "M: Certainly. Do you have the reservation number?",
        "W: Sure, it’s 219.",
        "M: That’s a reservation for Sally Menkel. Is that right?",
        "W: Yes, that’s right. I’d like to change the check-in date from September 15 to September 16.",
        "M: Certainly. I can make that change for you. Is that the only change?",
        "W: No, the check-out date will also change from the 23rd to the 24th.",
        "M: No problem. We have you arriving on the 16th of September and leaving the 24th of September — altogether, eight nights. Will there be anything else?",
        "W: Yes. Instead of a courtyard room, I’d like a room with a view, preferably on an upper floor.",
        "M: I can certainly change that for you, but there will be a change in the room rate. The new rate is $199 per night, instead of the original $179.",
        "W: That’s OK. These are all the changes. Thank you very much.",
        "M: You’re welcome. Have a nice day!",
    ],
    source: "2016年高考全国卷(一) · 11"
},
{
    q: 'How much will the woman pay for her room per night?',
    o: ["A. $179", "B. $199"," C. $219"],
    answer: 2,
    audio: 19_20,
    origin: [
        "M: Hello, Milton Hotel Reservations. How may I assist you?",
        "W: Hi, I’m calling to make some changes to an existing reservation.",
        "M: Certainly. Do you have the reservation number?",
        "W: Sure, it’s 219.",
        "M: That’s a reservation for Sally Menkel. Is that right?",
        "W: Yes, that’s right. I’d like to change the check-in date from September 15 to September 16.",
        "M: Certainly. I can make that change for you. Is that the only change?",
        "W: No, the check-out date will also change from the 23rd to the 24th.",
        "M: No problem. We have you arriving on the 16th of September and leaving the 24th of September — altogether, eight nights. Will there be anything else?",
        "W: Yes. Instead of a courtyard room, I’d like a room with a view, preferably on an upper floor.",
        "M: I can certainly change that for you, but there will be a change in the room rate. The new rate is $199 per night, instead of the original $179.",
        "W: That’s OK. These are all the changes. Thank you very much.",
        "M: You’re welcome. Have a nice day!",
    ],
    source: "2016年高考全国卷(一) · 12"
}]